### ISSUE TITLE
Starting Energy Issue

### ISSUE THREAD

**Issue by jillfrost** [steventopper/TransRot#3]
Hi Steven,
I'm currently making plots of the energy of two buckyballs versus the distance they are apart. To do this, I made a code that takes the output positions from a TransRot run, moves them by certain increments, and then outputs an .xyz file to use an input file in TransRot again.  I then run a calculation using the input file in TransRot to just get the starting energy. When I do this I expect the starting energy to be the same as the energy that was given for that output, however, I am finding that the energy it is giving is much lower. 

**To Reproduce**
1. Take the output file of a run and format it to be an input file.
2. Set up the config file (included) to output only the starting energy and use the input file.
3. Run the calculation.
4. Compare the energy value from the original output to the energy from the shortened starting energy calculation.

**Expected behavior**
I expected the energy from the original output to be the same as the starting energy when using it as an input file. For example, in one run of a two buckyball cluster, I got an energy output from a tooth to be -8.0965 kcal/mol. I formatted that to be an input file to find the starting energy and it outputs -8.246 kcal/mol.

**Screenshots**
I've included an output of a tooth with the energy as an example. From that, I formatted that output as an input file which is also included. I've added the config file and a picture of the starting energy output that seems to be wrong

**Config/Dbase Files**
Everything included in this folder: https://drive.google.com/drive/folders/1rCNL6c2-xCAu52OLhJA70fBAFxVCd-a0?usp=share_link

**Desktop (please complete the following information):**
 - OS: iOS
 - Version: Ventura 13.4

**TransRot Version**
- Version: 1.6.3

**Additional context**

**Comment by jillfrost** [comment]
After leaving this issue, I redid everything to check it one last time and it seems to have worked! My apologies; it must've been an issue on my end. I'll let you know if I run into anything else. Thank you!

**Comment by steventopper** [comment]
OK, no worries. Definitely let me know if this issue or any other issues come up.
