### ISSUE TITLE
[Feature] table of all interaction parameters

### ISSUE THREAD

**Issue by rqtopper** [steventopper/TransRot#4]
It would be really helpful for purposes of fully documenting a calculation if TransRot were to create a table of all of the pairwise interaction potential parameters used in the simulation, including all terms calculated using combination rules. This could either be in a file of its own or as part of the log.txt output.

This will allow the user to compare the parameters actually used in the simulation with parameters from other sources. It will also allow the user to more completely document the work.

**Comment by steventopper** [comment]
Here's an example of the pairwise interaction parameter output I've created. Let me know if this suits your needs.
```
N	H	0.0	0.0	0.0	0.0
N	Cl	0.0	0.0	3099.1447746519393	6911464.963027542
H	H	0.0	0.0	0.0	0.0
H	Cl	0.0	0.0	0.0	0.0
O	H	0.0	0.0	0.0	0.0
N	N	0.0	0.0	801.3257	944298.3796
Cl	H	0.0	0.0	0.0	0.0
O	Cl	0.0	0.0	2670.6432816052015	5425977.317740446
N	O	0.0	0.0	690.5308569597016	741339.4434172494
H	N	0.0	0.0	0.0	0.0
H	O	0.0	0.0	0.0	0.0
Cl	Cl	0.0	0.0	11986.0106	5.058607424E7
O	N	0.0	0.0	690.5308569597016	741339.4434172494
Cl	N	0.0	0.0	3099.1447746519393	6911464.963027542
O	O	0.0	0.0	595.055	582002.6617
Cl	O	0.0	0.0	2670.6432816052015	5425977.317740446
```

**Comment by rqtopper** [comment]
This will be better if column titles are added and all numbers are column aligned. Duplication should be avoided in the table. For example entries are not needed for both "N---Cl" and "Cl---N".
Also need a list of the charges used. These probably should be given in a second table. It should be made clear what units these numbers are in (energies in kcal/mol, distances in Angstroms, charges in atomic units). The formulas of the atoms/molecules should be provided (H2O, NH4+, Cl-), Finally, the value of kappa used by the code in the calculation of the Coulomb terms should also be provided here. The best order would probably be 
1. list of formulas of molecules
2. Statement of units used in the following quantities
3. kappa value
4. List of atomic charges
5. Table of pair potential parameters
Thank you!

**Comment by steventopper** [comment]
Updated version:
```
Molecular Formulas:
NH4+
Cl-
H2O

Units:
Distances in Angstroms, charges in atomic charge units, energies in Kcal/mol

Atomic Charges:
Symbol  Charge
N      -0.4
H       0.35
Cl     -1.0
O      -0.834

Pair Potentials:
Particles   A           B           C           D
N   H       0.000000    0.000000    0.000000    0.000000
N   Cl      0.000000    0.000000    3099.144    6911464.
H   H       0.000000    0.000000    0.000000    0.000000
H   Cl      0.000000    0.000000    0.000000    0.000000
O   H       0.000000    0.000000    0.000000    0.000000
N   N       0.000000    0.000000    801.3257    944298.3
O   Cl      0.000000    0.000000    2670.643    5425977.
N   O       0.000000    0.000000    690.5308    741339.4
Cl  Cl      0.000000    0.000000    11986.01    5.058607
O   O       0.000000    0.000000    595.0550    582002.6
```

**Comment by rqtopper** [comment]
Because of the weird way that sig figs work, we need the C and D
parameters to 3 more sig figs. I understand it's easiest to do them all the
same, so can we have (A,B,C,D) to three additional places? That should do
the trick.

Also, we need a line that says something like "Kappa =" and gives the value
of Kappa. Everything else is perfect.

Robert Q. Topper
***@***.***
http://engfac.cooper.edu/topper

**Comment by steventopper** [comment]
Updated:
```
Molecular Formulas:
NH4+
Cl-
H2O

Units:
Distances in Angstroms, charges in atomic charge units, energies in Kcal/mol

Kappa = 332.0637133

Atomic Charges:
Symbol  Charge
N      -0.4
H       0.35
Cl     -1.0
O      -0.834

Pair Potentials:
Particles   A           B           C           D
N   H       0.000000    0.000000    0.000000000    0.000000000
N   Cl      0.000000    0.000000    3099.144774    6911464.963
H   H       0.000000    0.000000    0.000000000    0.000000000
H   Cl      0.000000    0.000000    0.000000000    0.000000000
O   H       0.000000    0.000000    0.000000000    0.000000000
N   N       0.000000    0.000000    801.3257000    944298.3796
O   Cl      0.000000    0.000000    2670.643281    5425977.317
N   O       0.000000    0.000000    690.5308569    741339.4434
Cl  Cl      0.000000    0.000000    11986.01060    5.058607424
O   O       0.000000    0.000000    595.0550000    582002.6617
```
