### ISSUE TITLE
[Feature] Calculate thermodynamic averages of energy, squared energy, and heat capacity

### ISSUE THREAD

**Issue by rqtopper** [steventopper/TransRot#5]
When analyzing annealing calculations, sometimes we see preliminary evidence of one or more higher-energy structures while annealing. We would like to assess whether these structures are being sampled properly by adding a feature to calculate the heat capacity as a function of temperature. Actually, what we want is a "configurational" heat capacity, because we do not generally need to include the (constant) kinetic energy contributions when carrying out this analysis (and if we ever did, those would be trivial to add after the fact).

To address this, when the user requests a calculation to be carried out at a fixed ("static") temperature we would like the following three quantities to be calculated and reported:

1. The average interaction energy, < V >
2. The average of the squared interaction energy, <V<sup>2</sup>>
3. The configurational heat capacity, C = (<V<sup>2</sup>> - < V ><sup>2</sup>) / (k<sub>B</sub>T<sup>2</sup>)

These three numbers could be reported in the log.txt file, or alternately written to a separate file. 

An important note: the two averages < V > and <V<sup>2</sup>> must not use all of the Monte Carlo-generated samples. The energies of the first n<sub>eq</sub> configurations (these are called "equilibration configurations") of the total N configurations used to simulate the system at the desired temperature should be excluded from computing the averages. The value of n<sub>eq</sub> (which must be greater than zero and less than N) would be specified by the user in the config.txt file. As an example, a user might want to run a calculation using N=160,000 samples and also specify that n<sub>eq</sub> = 10,000 samples. The calculation would run for 160,000 Monte Carlo loops, but the energies and squared energies of the first 10,000 configurations would not be included in the averages of V and V<sup>2</sup>. The remaining 150,000 samples would be the only samples used for computing the averages (and the running sum would ultimately be divided by 150,000).

Assuming N is large enough, equilibration is not an important thing for simulated annealing work but it is critically important for calculating thermodynamic averages. Also, please note that all samples are included in the thermodynamic averages, whether or not the move is accepted. This has the effect of adding the same number twice into the average when a move is rejected; this is necessary. See the figure below from our paper on Monte Carlo methods. 

Ultimately it would be useful to calculate these averages at every temperature during an annealing calculation; perhaps this could be planned for the future. 

Image from Topper et al., https://onlinelibrary.wiley.com/doi/abs/10.1002/0471466638.ch1 

![image](https://github.com/user-attachments/assets/ecdca64c-e554-49b9-822a-551d1fcd381d)

**Comment by Aragolt** [comment]
I'm looking at implementing this for the output:

Configurable Heat Capacity for 20.0K, Tooth 4/4, Point 1/10
Average Interaction Energy: -14424.740398367789
Average Squared Interaction Energy: 3.2625627290555865E8
Configurable Heat Capacity: -2268.6840321755626

This would be repeated in the log file for each tooth/point (i.e. each individual temperature); if you just want one output for the entire run (as might be wanted for static temperature simulations) you can set the number of teeth and points per tooth to 1. Let me know if this output looks fine; we can discuss other layouts as well.

A few questions: 
- How many decimal places should this output be to?
- Some of the resulting numbers are given using scientific notation (see above, Average Squared Interaction Energy). Is this fine to leave as-is, or should it be fully expanded?
- For the last point in a tooth, annealing is typically being run at (or very close to) 0K, which results in extremely large/small configurational heat capacities, such as -9.459720915889738E34 or -Infinity (when dividing by 0). This also occurs during 0K finales. Is this an intended result, and if not, how should this be handled?

**Comment by steventopper** [comment]
I'm looking at implementing this for the output:

Configurable Heat Capacity for 20.0K, Tooth 4/4, Point 1/10
Average Interaction Energy: -14424.740398367789
Average Squared Interaction Energy: 3.2625627290555865E8
Configurable Heat Capacity: -2268.6840321755626

This would be repeated in the log file for each tooth/point (i.e. each individual temperature); if you just want one output for the entire run (as might be wanted for static temperature simulations) you can set the number of teeth and points per tooth to 1. Let me know if this output looks fine; we can discuss other layouts as well.

A few questions:

- How many decimal places should this output be to?
- Some of the resulting numbers are given using scientific notation (see above, Average Squared Interaction Energy). Is this fine to leave as-is, or should it be fully expanded?
- For the last point in a tooth, annealing is typically being run at (or very close to) 0K, which results in extremely large/small configurational heat capacities, such as -9.459720915889738E34 or -Infinity (when dividing by 0). This also occurs during 0K finales. Is this an intended result, and if not, how should this be handled?

**Comment by rqtopper** [comment]
Thank you. Before answering those questions, let's call it "**Configurational** Heat Capacity, not "Configurable". 

If you are going to provide us with a heat capacity at every temperature, three things:
(1) we would want to suppress that output completely when the user does not require any equilibration. 
(2) We really only need  the average energy (< V >) and C to be in the output, so don't bother reporting <V^2>.
(3) The output of (< V >), C should be provided in columns, so that it can be read into a spreadsheet readily. This could be in a separate file. Is that possible?

As to your questions:

1. The number of decimal places shown in your example is fine.
2. Yes, it is okay for the code to just default to scientific notation for large or small numbers.
3. The temperature should never be allowed to equal 0K in a run - this method is meant only for use at finite and nonzero temperature.

**Comment by steventopper** [comment]
I've moved the output to a new file named configurational_heat_capacity.txt. Here's an example output of this file for a non-static temperature annealing (columns are Temperature, Average Energy, Configurational Heat Capacity in that order):

```
10000.0	-399.97750831502196	-0.010379491910059688
8888.89	-815.4491168103854	2.095911448918407
7777.78	-1236.4514435403191	8.438651001027416
6666.67	-1669.6533851617266	23.603380478211985
5555.56	-2111.6151257677097	58.03600053454879
4444.44	-2575.715585416029	140.592050779474
3333.33	-3051.953517000839	361.0333192659229
2222.22	-3559.3276565853366	1127.8891881941802
1111.11	-4099.409967578446	6078.631076443244
8000.0	-5118.629516710535	186.89716276762076
7111.11	-5547.5550191383845	280.2270061588138
6222.22	-5985.852347192143	429.2072530403935
5333.33	-6436.391260501989	679.6022399917363
4444.44	-6892.184622270445	1128.0835463826777
3555.56	-7375.017592763479	2027.5435000320874
2666.67	-7875.421216313981	4126.820236439285
1777.78	-8405.47569731111	10614.61847521474
888.89	-8973.958331573984	48544.994780593224
6400.0	-10024.677669924602	1174.7446232975
5688.89	-10472.867167928342	1626.4973390585983
4977.78	-10933.587885525114	2320.3740547083817
4266.67	-11394.197466013075	3436.697401142652
3555.56	-11869.376960304482	5379.86394840781
2844.44	-12364.069654175122	9136.41268402541
2133.33	-12882.5033928548	17659.99203449841
1422.22	-13431.92407665188	43256.69761283006
711.11	-14008.291982541177	188434.92559697214
5120.0	-15058.012010404143	4209.803549589998
4551.11	-15527.438827332273	5671.481090755553
3982.22	-15998.584443817273	7871.9266641926715
3413.33	-16485.869095710677	11387.987280388776
2844.44	-16983.59722257594	17419.384354312737
2275.56	-17482.307405271236	28863.978917840916
1706.67	-18001.83486227824	54452.04505203389
1137.78	-18546.88586727326	130145.29640074607
568.89	-19130.518901382475	554243.4910257629
```

**Comment by steventopper** [comment]
Also, here's an example output file you can expect from a static temperature simulation:
```
10000.0	-384.83569685684245	-0.047257139223782295
```
